# Heavily based on druid's workflow at
#   https://github.com/xi-editor/druid/blob/76fba835605aa1c51e4f541d6a08ff94542f9b0a/.github/workflows/ci.yml

name: Package

on:
  push:
    branches: [main]
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_package:
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-2019]
    name: package app
    steps:
      - uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          ./.github/workflows/env-setup.sh CREATE_RELEASE
          ./.github/workflows/env-setup.sh ARTIFACT_SUFFIX
        shell: bash

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-cargo-

      - name: install libgtk-3-dev libx11-dev
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libx11-dev
        if: contains(matrix.os, 'ubuntu')

      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal
          override: true

      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: install cargo bundle
        if: contains(matrix.os, 'macOS')
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-bundle

      - name: build mac package
        if: contains(matrix.os, 'macOS')
        uses: actions-rs/cargo@v1
        with:
          command: bundle
          args: --release

      - name: create dmg
        if: contains(matrix.os, 'macOS')
        run: |
          mkdir -p target/release/bundle/osx/Pollendina${{env.ARTIFACT_SUFFIX}}
          cp -a target/release/bundle/osx/Pollendina.app \
            target/release/bundle/osx/Pollendina${{env.ARTIFACT_SUFFIX}}
          hdiutil create \
            target/release/bundle/osx/Pollendina-mac${{env.ARTIFACT_SUFFIX}}.dmg \
            -srcfolder target/release/bundle/osx/Pollendina${{env.ARTIFACT_SUFFIX}} \
            -ov

      - name: upload mac package
        if: contains(matrix.os, 'macOS')
        uses: actions/upload-artifact@v2
        with:
          name: Pollendina-mac${{env.ARTIFACT_SUFFIX}}.dmg
          path: target/release/bundle/osx/Pollendina-mac${{env.ARTIFACT_SUFFIX}}.dmg

      - name: upload mac release artifact
        if: contains(matrix.os, 'macOS') && env.CREATE_RELEASE == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: Pollendina-mac${{env.ARTIFACT_SUFFIX}}.dmg
          asset_path: target/release/bundle/osx/Pollendina-mac${{env.ARTIFACT_SUFFIX}}.dmg
          asset_content_type: application/octet-stream

      - name: install cargo wix
        if: contains(matrix.os, 'windows')
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-wix

      - name: build windows installer
        if: contains(matrix.os, 'windows')
        uses: actions-rs/cargo@v1
        with:
          command: wix
          args: --nocapture --output=target/wix/pollendina-win${{env.ARTIFACT_SUFFIX}}.msi

      # this will need to be updated every release
      - name: upload windows installer
        if: contains(matrix.os, 'windows')
        uses: actions/upload-artifact@v2
        with:
          name: pollendina-win${{env.ARTIFACT_SUFFIX}}.msi
          path: target/wix/pollendina-win${{env.ARTIFACT_SUFFIX}}.msi

      - name: upload windows release artifact
        if: contains(matrix.os, 'windows') && env.CREATE_RELEASE == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: pollendina-win${{env.ARTIFACT_SUFFIX}}.msi
          asset_path: target/wix/pollendina-win${{env.ARTIFACT_SUFFIX}}.msi
          asset_content_type: application/octet-stream

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          ./.github/workflows/env-setup.sh CREATE_RELEASE
        shell: bash

      - name: Create release
        if: env.CREATE_RELEASE == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Pollendina ${{ github.ref }}
          draft: false
          prerelease: true
